version: '3'

services:

### Workspace Utilities Container ###########################

    workspace:
        image: rpopuc/workspace:7.2
        volumes:
            - ${APPLICATION}:/var/www
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        image: rpopuc/php-fpm:7.2
        volumes:
            - ${APPLICATION}:/var/www
            - ./config/php-fpm/php.ini:/usr/local/etc/php/php.ini
        expose:
            - "9000"
        depends_on:
            - workspace
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"

### Nginx Server Container ##################################

    nginx:
        image: rpopuc/nginx:alpine
        volumes:
            - ${APPLICATION}:/var/www
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm

### PostgreSQL Container ####################################

    postgres:
        image: rpopuc/postgres:10
        volumes:
            - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

### Redis Container #########################################

    redis:
        image: rpopuc/redis:4-alpine
        volumes:
            - ${DATA_SAVE_PATH}/redis:/data

### Laravel Echo Server #######################################

    laravel-echo:
        image: rpopuc/laravel-echo-server:7.2
        volumes:
            - ./config/laravel-echo/laravel-echo-server.json:/app/laravel-echo-server.json:ro
        ports:
            - "${LARAVEL_ECHO_SERVER_PORT}:6001"
        links:
            - redis
